	<?php
	
	// drupal_add_css(drupal_get_path('module', 'zoomla') . '/css/global.css');
	function zoomla_form_alter(&$form, &$form_state, $form_id) {
		
	}
	
	
	function zoomla_form_contact_form_node_form_alter(&$form, &$form_state, $form_id) {
		drupal_set_title('联系我们', PASS_THROUGH);
		$form['actions']['submit']['#submit'][0]="_zoomla_form_form_node_form_submit";
	}
	
	function _zoomla_form_form_node_form_submit($form, &$form_state){
		$message='感谢您的留言,我们会尽快与您联系!';
		$node = node_form_submit_build_node($form, $form_state);
		$insert = empty($node->nid);
		node_save($node);
		$node_link = l(t('view'), 'node/' . $node->nid);
		$watchdog_args = array('@type' => $node->type, '%title' => $node->title);
		$t_args = array('@type' => node_type_get_name($node), '%title' => $node->title);
		
		if ($insert) {
			watchdog('content', '@type: added %title.', $watchdog_args, WATCHDOG_NOTICE, $node_link);
			drupal_set_message($message);
		}
		else {
			watchdog('content', '@type: updated %title.', $watchdog_args, WATCHDOG_NOTICE, $node_link);
			drupal_set_message($message);
		}
		if ($node->nid) {
			$form_state['values']['nid'] = $node->nid;
			$form_state['nid'] = $node->nid;
			$form_state['redirect'] = node_access('view', $node) ? 'node/' . $node->nid : '<front>';
		}
		else {
			// In the unlikely case something went wrong on save, the node will be
			// rebuilt and node form redisplayed the same way as in preview.
			drupal_set_message(t('The post could not be saved.'), 'error');
			$form_state['rebuild'] = TRUE;
		}
		// Clear the page and block caches.
		cache_clear_all();
			
	}
	
	function zoomla_menu() {
		
		$items['aaa'] = array(
				'page callback' => '_zoomla_aaa',
				'access callback'=>true
		);
		return $items;
	}
	
	function _zoomla_aaa(){
		ctools_set_no_blocks(true);
			return "dddd";
		
	}
	
	
